### ISSUE TITLE
Stack builder can not find list files if the file names start with a number 

### ISSUE THREAD

**Issue by raacampbell** [alexanderbrown/masiv#11]
This has apparently happened with data in the MF lab when the sample ID is a number. e.g. "15".

**Comment by alexanderbrown** [comment]
Not something I've noticed. Where does it fail?

**Comment by raacampbell** [comment]
Don't know. I only know about this second-hand. I will invite people to contribute to this issue if they want it fixed.

**Comment by ghost** [comment]
I haven't tested longer filenames starting with numbers, however if the sample name is something simple, eg. "17," even if the list files are present, MaSIV will complain that it cannot find them. The channel options will also not be present for building after clicking "New." Renaming the sample (and all sub-folder/sampleID references to it) to something like: "AB_17" fixes the issue.

**Comment by raacampbell** [comment]
So the image list files start with the characters `17_`

**Comment by ghost** [comment]
As does the yml, the "stackName" field in the yml, and the "sampleID" field in our mosaic files.

**Comment by alexanderbrown** [comment]
OK so one explanation is that matlab variables can't begin with a number. Because the `masivMeta` object uses the channel name to create a structure, it can't create a variable

**Comment by raacampbell** [comment]
Yeah, something like this screwed me too in StitchIt when those samples were acquired. In general we don't name our sample IDs with strings that start with a number. So this was a bit of a great occurrence. It will be impossible to do with out custom acquisition software, but TissueVision's software allows it. 

Shall we fix this in MaSIV or should we just be crap and create a FAQ that tells users not to have sample IDs that start with a number?

**Comment by alexanderbrown** [comment]
I'm seeing if i can come up with a fix. If it's a ballache we'll take the easy route, but i'll just make sure that there isn't an easy fix

**Comment by raacampbell** [comment]
The [easy route](https://github.com/alexanderbrown/masiv/wiki/FAQ) is waiting for you if you need it.

**Comment by alexanderbrown** [comment]
This may now be fixed in 19e9f26d8f2a3eab0d0ec18d9f76442486604eee. @Synpaptic please confirm.

**Comment by raacampbell** [comment]
Doesn't fix it for me. I just [mocked this up](https://www.dropbox.com/s/wfodr4sukg4avyc/01_MaSIV.tar.gz?dl=0) and it fails with it.

**Comment by ghost** [comment]
Works for me

**Comment by ghost** [comment]
Confirmed. Rolling back to previous version broke it, and new fixes it again.

**Comment by alexanderbrown** [comment]
Worked on my mocked up data too. Rob you sure your mocked data doesn't have
another error?

**Comment by raacampbell** [comment]
I think your fix fails if the sample ID is "01". If I rename everything to "10" then it works. I don't know why `isnumeric` would fail under those circumstances. Maybe there is a different failure point if the first character is zero. Try with the mock up I sent, above.

**Comment by ghost** [comment]
Yep, same thing happens here. I was testing with "10," but "01" breaks it

**Comment by alexanderbrown** [comment]
Odd. Should be fixable. I'll look in to it

**Comment by alexanderbrown** [comment]
Ok I can guess why that is the case. I'll write a fix later today or
tomorrow

**Comment by alexanderbrown** [comment]
Should now be resolved in 2b357ebb3a1fda44691dacbcd08b6b206d87d0ae

The problem was caused when the stackname was read from yaml, converted to numeric and then back in to string, therefore losing the leading zero. I've tweaked the yaml reader to keep any seemingly numeric values as string if they contain leading zeros. 

It's possible that this is unwise and could cause some unforeseen problems, but the chances are low and I'm hoping that writing this will reduce those chances further...

**Comment by raacampbell** [comment]
I double-checked that I have the changes pulled but I still don't see the stack appear. At the command line I get this:
```
>> masiv.yaml.readSimpleYAML('01_Meta.yml')

ans = 

  struct with fields:

             VoxelSize: [1×1 struct]
             stackName: 1
    imageBaseDirectory: '../'
```

and my YAML file contains:

```
VoxelSize:
    x: 1
    y: 1
    z: 9

stackName: 01
imageBaseDirectory: ../
```

So it's definitely importing it as a number. If I get a chance I'll look into this too. If it keeps being annoying we can just list as a known bug and move on.

**Comment by alexanderbrown** [comment]
Sorry I tried to replicate this but your example is no longer available

**Comment by raacampbell** [comment]
Sorry, I put it back. I also see I can drag into a comment to attach it. So here it is:
[01_MaSIV.tar.gz](https://github.com/alexanderbrown/masiv/files/691420/01_MaSIV.tar.gz)

**Comment by alexanderbrown** [comment]
Should now be fixed in 8e2739fe3dee4ed5e56135331ad47df11dc53e58 (I actually tested it this time)

Closing

**Comment by raacampbell** [comment]
See #15
